#!/bin/bash

if [ -z `which tmux` ]
then
	echo 'require tmux';
	exit 1;
fi

if [ -z `which watch` ]
then
	echo 'require watch';
	exit 1;
fi

if [ -z `which deno` ]
then
	echo 'require deno';
	exit 1;
fi

if [ -z `which fish` ]
then
	shell='bash';
else
	shell='fish';
fi

if [ -z $TMUX ]
then
	tmux new-session $shell -C "git watch $@";
	
	exit 0;
fi

case $1 in
	conflict)
		tmux split-window -h -p20 watching --grep='^U' git changes;
		tmux select-pane -t0;
	;;
	path)
		tmux split-window -h -p40 watching git changes -- $2;
		tmux split-window -v -p30 watching git tree-branch --color=always -- $2;
		tmux select-pane -t1;
		tmux split-window -h -p30 watching git branches -- $2;
		tmux select-pane -t1;
		tmux split-window -v -p20 watching git reflog -a --color=always -- $2;
		tmux select-pane -t0;
		tmux split-window -v -p80 -b watching git tree --color=always -- $2;
		tmux select-pane -t1;
	;;
	*)
		tmux split-window -h -p40 watching git changes;
		tmux split-window -v -p30 watching git tree-branch --color=always;
		tmux select-pane -t1;
		tmux split-window -h -p30 watching git branches;
		tmux select-pane -t1;
		tmux split-window -v -p20 watching git reflog -a --color=always;
		tmux select-pane -t0;
		tmux split-window -v -p80 -b watching git tree --color=always;
		tmux select-pane -t1;
	;;
esac

clear;
