#!/bin/bash

if [[ $(which tmux) == '' ]]
then
	echo 'require tmux';
	exit 1;
fi

if [[ $(which watch) == '' ]]
then
	echo 'require tmux';
	exit 1;
fi

if [[ $TMUX == '' ]]
then
	echo 'please run this command in tmux';
	exit 1;
fi

tmux split-window -h -p50 watch -ct -n0.5 git -c color.status=always s;
tmux split-window -v -p80 watch -ct -n0.5 git tree --color=always;
tmux select-pane -t0;
