#!/bin/bash

if [[ $(which tmux) == '' ]]
then
	echo 'require tmux';
	exit 1;
fi

if [[ $(which watch) == '' ]]
then
	echo 'require watch';
	exit 1;
fi

if [[ $(which deno) == '' ]]
then
	echo 'require deno';
	exit 1;
fi

if [[ $(which git-tree-watching) == '' ]]
then
	echo 'must deploy git-tree-watching';
	exit 1;
fi

if [[ $TMUX == '' ]]
then
	echo 'please run this command in tmux';
	exit 1;
fi

tmux split-window -h -p50 watch -ct -n0.5 git -c color.status=always s;
tmux split-window -v -p80 git tree-watching;
tmux select-pane -t0;
