#!/bin/bash

if [[ $1 && $1 != 'HEAD' ]]
then
	ref=$(git show-ref $1 | head -1 | sed -r 's/^\w+\s(\S+)/\1/')
	
	if [[ $ref ]]
	then
		git symbolic-ref HEAD $ref
	else
		ref=$(git rev-list -1 $1)
		git update-ref --no-deref HEAD $ref
	fi
else
	ref=$(git show-ref --head HEAD | head -1 | sed -r 's/^\w+\s(\S+)/\1/')
fi

if [[ $ref ]]
then
	git read-tree $ref
fi

if [ -f "$(git rev-parse --show-toplevel)/.gitignore" ]
then
	git checkout -- "$(git rev-parse --show-toplevel)/.gitignore"
fi
